#!/bin/sh

function secret {
    output="${HOME}/$(basename ${1}).$(date +%F).enc"
    gpg --encrypt --armor \
        --output ${output} \
        -r \
        "${1}" && echo "${1} -> ${output}"
}

function reveal {
    output=$(echo "${1}" | rev | cut -c16- | rev)
    gpg --decrypt --output ${output} "${1}" && echo "${1} -> ${output}"
}

function myip {
    curl -sq "https://icanhazip.com/"
}
